spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/event
  application:
    name: organization-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
server:
  port: 8084

springdoc:
  swagger-ui:
    path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
